spring.application.name=game
spring.web.resources.static-locations=file:../client/,classpath:/static/
spring.web.resources.cache.cachecontrol.no-cache=true
turnstile.secret=${TURNSTILE_SECRET:1x0000000000000000000000000000000AA}
