package com.mafia.game.room;

import com.mafia.game.model.GamePhase;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class RoomManagerTest {

    @Autowired
    private RoomManager roomManager;

    @BeforeEach
    void setUp() {
        // Clear all rooms before each test
        roomManager.getAllRooms().keySet().forEach(roomManager::removeRoom);
    }

    @Test
    void testCreateRoom_WithCustomJoinCode() {
        // Given
        String customJoinCode = "TEST123";
        int minPlayers = 4;
        int maxPlayers = 8;

        // When
        Room room = roomManager.createRoom(customJoinCode, minPlayers, maxPlayers);

        // Then
        assertNotNull(room);
        assertNotNull(room.getId());
        assertEquals(customJoinCode, room.getJoinCode());
        assertEquals(GamePhase.LOBBY, room.getPhase());
        assertEquals(minPlayers, room.getMinPlayers());
        assertEquals(maxPlayers, room.getMaxPlayers());
        assertNotNull(room.getPlayers());
        assertTrue(room.getPlayers().isEmpty());
    }

    @Test
    void testCreateRoom_WithAutoGeneratedJoinCode() {
        // Given
        int minPlayers = 3;
        int maxPlayers = 6;

        // When
        Room room = roomManager.createRoom(null, minPlayers, maxPlayers);

        // Then
        assertNotNull(room);
        assertNotNull(room.getId());
        assertNotNull(room.getJoinCode());
        assertEquals(6, room.getJoinCode().length());
        assertTrue(room.getJoinCode().matches("[A-Z0-9]{6}"));
        assertEquals(GamePhase.LOBBY, room.getPhase());
        assertEquals(minPlayers, room.getMinPlayers());
        assertEquals(maxPlayers, room.getMaxPlayers());
    }

    @Test
    void testCreateRoom_WithBlankJoinCode() {
        // Given
        String blankJoinCode = "   ";
        int minPlayers = 5;
        int maxPlayers = 10;

        // When
        Room room = roomManager.createRoom(blankJoinCode, minPlayers, maxPlayers);

        // Then
        assertNotNull(room);
        assertNotNull(room.getJoinCode());
        assertEquals(6, room.getJoinCode().length());
        assertTrue(room.getJoinCode().matches("[A-Z0-9]{6}"));
    }

    @Test
    void testGetRoom_ById() {
        // Given
        Room createdRoom = roomManager.createRoom("GETTEST", 4, 8);
        UUID roomId = createdRoom.getId();

        // When
        Optional<Room> retrievedRoom = roomManager.getRoom(roomId);

        // Then
        assertTrue(retrievedRoom.isPresent());
        assertEquals(createdRoom, retrievedRoom.get());
        assertEquals(roomId, retrievedRoom.get().getId());
    }

    @Test
    void testGetRoom_ById_NotFound() {
        // Given
        UUID nonExistentId = UUID.randomUUID();

        // When
        Optional<Room> room = roomManager.getRoom(nonExistentId);

        // Then
        assertFalse(room.isPresent());
    }

    @Test
    void testGetRoomByJoinCode() {
        // Given
        String joinCode = "JOINTEST";
        Room createdRoom = roomManager.createRoom(joinCode, 3, 7);

        // When
        Optional<Room> retrievedRoom = roomManager.getRoomByJoinCode(joinCode);

        // Then
        assertTrue(retrievedRoom.isPresent());
        assertEquals(createdRoom, retrievedRoom.get());
        assertEquals(joinCode, retrievedRoom.get().getJoinCode());
    }

    @Test
    void testGetRoomByJoinCode_CaseInsensitive() {
        // Given
        String joinCode = "CASETEST";
        Room createdRoom = roomManager.createRoom(joinCode, 4, 8);

        // When
        Optional<Room> retrievedRoom = roomManager.getRoomByJoinCode("casetest");

        // Then
        assertTrue(retrievedRoom.isPresent());
        assertEquals(createdRoom, retrievedRoom.get());
    }

    @Test
    void testGetRoomByJoinCode_NotFound() {
        // Given
        String nonExistentCode = "NONEXIST";

        // When
        Optional<Room> room = roomManager.getRoomByJoinCode(nonExistentCode);

        // Then
        assertFalse(room.isPresent());
    }

    @Test
    void testGetRoomByJoinCode_NullInput() {
        // When
        Optional<Room> room = roomManager.getRoomByJoinCode(null);

        // Then
        assertFalse(room.isPresent());
    }

    @Test
    void testRemoveRoom() {
        // Given
        Room createdRoom = roomManager.createRoom("REMOVEME", 4, 8);
        UUID roomId = createdRoom.getId();
        String joinCode = createdRoom.getJoinCode();

        // Verify room exists
        assertTrue(roomManager.getRoom(roomId).isPresent());
        assertTrue(roomManager.getRoomByJoinCode(joinCode).isPresent());

        // When
        roomManager.removeRoom(roomId);

        // Then
        assertFalse(roomManager.getRoom(roomId).isPresent());
        assertFalse(roomManager.getRoomByJoinCode(joinCode).isPresent());
    }

    @Test
    void testRemoveRoom_NonExistent() {
        // Given
        UUID nonExistentId = UUID.randomUUID();
        int initialRoomCount = roomManager.getAllRooms().size();

        // When
        roomManager.removeRoom(nonExistentId);

        // Then
        assertEquals(initialRoomCount, roomManager.getAllRooms().size());
    }

    @Test
    void testGetAllRooms() {
        // Given
        Room room1 = roomManager.createRoom("ALLTEST1", 3, 6);
        Room room2 = roomManager.createRoom("ALLTEST2", 4, 8);
        Room room3 = roomManager.createRoom("ALLTEST3", 5, 10);

        // When
        var allRooms = roomManager.getAllRooms();

        // Then
        assertEquals(3, allRooms.size());
        assertTrue(allRooms.containsKey(room1.getId()));
        assertTrue(allRooms.containsKey(room2.getId()));
        assertTrue(allRooms.containsKey(room3.getId()));
        assertEquals(room1, allRooms.get(room1.getId()));
        assertEquals(room2, allRooms.get(room2.getId()));
        assertEquals(room3, allRooms.get(room3.getId()));
    }

    @Test
    void testGetAllRooms_Empty() {
        // When
        var allRooms = roomManager.getAllRooms();

        // Then
        assertNotNull(allRooms);
        assertTrue(allRooms.isEmpty());
    }

    @Test
    void testRoomIsolation() {
        // Given
        Room room1 = roomManager.createRoom("ISOLATE1", 3, 6);
        Room room2 = roomManager.createRoom("ISOLATE2", 4, 8);

        // When & Then
        assertNotEquals(room1.getId(), room2.getId());
        assertNotEquals(room1.getJoinCode(), room2.getJoinCode());
        assertEquals(GamePhase.LOBBY, room1.getPhase());
        assertEquals(GamePhase.LOBBY, room2.getPhase());
    }

    @Test
    void testJoinCodeUniqueness() {
        // Given
        String joinCode = "UNIQUE";
        Room room1 = roomManager.createRoom(joinCode, 3, 6);

        // When creating another room with same join code
        Room room2 = roomManager.createRoom(joinCode, 4, 8);

        // Then - should allow duplicate join codes (rooms can have same code)
        assertNotNull(room2);
        assertEquals(joinCode, room2.getJoinCode());
        assertNotEquals(room1.getId(), room2.getId());

        // But getRoomByJoinCode should return one of them (implementation detail)
        Optional<Room> retrieved = roomManager.getRoomByJoinCode(joinCode);
        assertTrue(retrieved.isPresent());
        // Note: This test documents current behavior - last created room wins
    }

    @Test
    void testCleanup_OnShutdown() {
        // Given - create some rooms
        Room room1 = roomManager.createRoom("CLEANUP1", 3, 6);
        Room room2 = roomManager.createRoom("CLEANUP2", 4, 8);
        Room room3 = roomManager.createRoom("CLEANUP3", 5, 10);

        // Verify rooms exist
        assertEquals(3, roomManager.getAllRooms().size());
        assertTrue(roomManager.getRoom(room1.getId()).isPresent());
        assertTrue(roomManager.getRoom(room2.getId()).isPresent());
        assertTrue(roomManager.getRoom(room3.getId()).isPresent());

        // When - simulate application shutdown cleanup
        roomManager.cleanup();

        // Then - all rooms should be cleared
        assertEquals(0, roomManager.getAllRooms().size());
        assertFalse(roomManager.getRoom(room1.getId()).isPresent());
        assertFalse(roomManager.getRoom(room2.getId()).isPresent());
        assertFalse(roomManager.getRoom(room3.getId()).isPresent());
        assertFalse(roomManager.getRoomByJoinCode("CLEANUP1").isPresent());
        assertFalse(roomManager.getRoomByJoinCode("CLEANUP2").isPresent());
        assertFalse(roomManager.getRoomByJoinCode("CLEANUP3").isPresent());
    }
}
